### ISSUE TITLE
One more puzzle on implementation of MMR.

### ISSUE THREAD

**Issue by HaFred** [nayeem8527/Visual-Object-Tracking-using-Multi-Target-Regression#2]
Hi Mr. Nayeem,
Sorry to bother you again!

After reading through your codes and some debugging, I am still confused about the kernel function part(mapping training data into RKHS). Would you like to explain on how you do the kernel function K and feature function /phi exactly? 

As far as I see, in this project you are not doing exact the same multi-target regression as Dr. Zhen proposed. Nevertheless, with the Gaussian noise frame samples extracting and corresponding gt scores, you can still implement a successful object tracker.

So I am just wondering, in your case, how do you do the RKHS mapping as Dr. Zhen proposed in his paper? Thank you!

**Comment by nayeem8527** [comment]
Hello Fred, 
Sorry for the late reply. In my project I have use the fHoG feature as my data and used gaussian mapping function to map the HoG data. And for the kernel function K as described in the paper, I have used the same kernel.

> We accomplish the kernel version of the multi-layer multi-target regression with the kernel matrix K= phi(X)'phi(X) defined in the RKHS space.

here, phi is my gaussian mapping function (I have used gaussian as it was helping in my problem, you can use any other mapping function according to your needs) and X is my feature vector from HoG.

As per paper I have used Algorithm1, alternating optimization with some tweeks for my tracking.

**Comment by HaFred** [comment]
Thank you for your explanation, that was very clear. Currently, I am doing some other project, I will try this one out in the future.
